// <auto-generated />
using System;
using EKYNOX_HEI.DATA.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EKYNOX_HEI.DATA.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260729161202_AiSettingDetail_addLineNrColumn")]
    partial class AiSettingDetail_addLineNrColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("EKYNOX_HEI.DATA.DataModel.AISetting", b =>
                {
                    b.Property<int>("LOGICALREF")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AI")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AINO")
                        .HasMaxLength(51)
                        .HasColumnType("TEXT");

                    b.Property<string>("APIKEY")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CREATEDATE")
                        .HasColumnType("TEXT");

                    b.Property<int>("CREATEDUSER")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ENDPOINT")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("METHODNAME")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MODIFIEDDATE")
                        .HasColumnType("TEXT");

                    b.Property<int>("MODIFIEDUSER")
                        .HasColumnType("INTEGER");

                    b.Property<int>("USINGSTATUS")
                        .HasColumnType("INTEGER");

                    b.HasKey("LOGICALREF");

                    b.ToTable("AISetting");
                });

            modelBuilder.Entity("EKYNOX_HEI.DATA.DataModel.AISettingDetail", b =>
                {
                    b.Property<int>("LOGICALREF")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AIMODELDESC")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("AIMODELNAME")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("AISETTINGREF")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CREATEDATE")
                        .HasColumnType("TEXT");

                    b.Property<int>("CREATEDUSER")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LINENR")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MODIFIEDDATE")
                        .HasColumnType("TEXT");

                    b.Property<int>("MODIFIEDUSER")
                        .HasColumnType("INTEGER");

                    b.HasKey("LOGICALREF");

                    b.ToTable("AISettingDetail");
                });

            modelBuilder.Entity("EKYNOX_HEI.DATA.DataModel.EducationAttendance", b =>
                {
                    b.Property<int>("LOGICALREF")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CREATEDATE")
                        .HasColumnType("TEXT");

                    b.Property<int>("CREATEDUSER")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DOCNO")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("EDUCATIONSTATUS")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EDUCATORREF")
                        .HasColumnType("INTEGER");

                    b.Property<int>("INSTUTIONREF")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MODIFIEDDATE")
                        .HasColumnType("TEXT");

                    b.Property<int>("MODIFIEDUSER")
                        .HasColumnType("INTEGER");

                    b.HasKey("LOGICALREF");

                    b.ToTable("EducationAttendance");
                });

            modelBuilder.Entity("EKYNOX_HEI.DATA.DataModel.EducationAttendanceDetail", b =>
                {
                    b.Property<int>("LOGICALREF")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CREATEDATE")
                        .HasColumnType("TEXT");

                    b.Property<int>("CREATEDUSER")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EDUCATIONATTENDANCEREF")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EDUCATIONDATE")
                        .HasColumnType("TEXT");

                    b.Property<int>("EDUCATIONNUMBER")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EDUCATIONTYPE")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("FILEDATA")
                        .HasColumnType("BLOB");

                    b.Property<string>("FILENAME")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("FILEPATH")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MODIFIEDDATE")
                        .HasColumnType("TEXT");

                    b.Property<int>("MODIFIEDUSER")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MODULETYPE")
                        .HasColumnType("INTEGER");

                    b.Property<int>("READANDEXCELPROCESS")
                        .HasColumnType("INTEGER");

                    b.HasKey("LOGICALREF");

                    b.ToTable("EducationAttendanceDetail");
                });

            modelBuilder.Entity("EKYNOX_HEI.DATA.DataModel.EducationAttendanceFileRead", b =>
                {
                    b.Property<int>("LOGICALREF")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CLASSNO")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CREATEDATE")
                        .HasColumnType("TEXT");

                    b.Property<int>("CREATEDUSER")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EDUCATIONATTENDANCEDETAILREF")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("MODIFIEDDATE")
                        .HasColumnType("TEXT");

                    b.Property<int>("MODIFIEDUSER")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NAME")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("SURNAME")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("LOGICALREF");

                    b.ToTable("EducationAttendanceFileRead");
                });

            modelBuilder.Entity("EKYNOX_HEI.DATA.DataModel.Institutions", b =>
                {
                    b.Property<int>("LOGICALREF")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ADDRESS")
                        .HasMaxLength(700)
                        .HasColumnType("TEXT");

                    b.Property<string>("CITY")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CODE")
                        .HasMaxLength(51)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CREATEDATE")
                        .HasColumnType("TEXT");

                    b.Property<int>("CREATEDUSER")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DISTRICT")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MODIFIEDDATE")
                        .HasColumnType("TEXT");

                    b.Property<int>("MODIFIEDUSER")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NAME")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("TOWN")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("LOGICALREF");

                    b.ToTable("Institutions");
                });

            modelBuilder.Entity("EKYNOX_HEI.DATA.DataModel.Users", b =>
                {
                    b.Property<int>("LOGICALREF")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EMAIL")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NAME")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("NR")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PASSWORD")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("PHONE")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("ROLE")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SURNAME")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("USERNAME")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("LOGICALREF");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
