// <auto-generated />
using System;
using EKYNOX_HEI.DATA.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EKYNOX_HEI.DATA.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260721145132_newTables")]
    partial class newTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("EKYNOX_HEI.DATA.DataModel.EducationAttendance", b =>
                {
                    b.Property<int>("LOGICALREF")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DATE_")
                        .HasColumnType("TEXT");

                    b.Property<string>("DOCNO")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EDUCATIONFULLNAME")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("FILENAME")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("FILEPATH")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("INSTUTIONREF")
                        .HasColumnType("INTEGER");

                    b.HasKey("LOGICALREF");

                    b.ToTable("EducationAttendance");
                });

            modelBuilder.Entity("EKYNOX_HEI.DATA.DataModel.Institutions", b =>
                {
                    b.Property<int>("LOGICALREF")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ADDRESS")
                        .HasMaxLength(700)
                        .HasColumnType("TEXT");

                    b.Property<string>("CITY")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CODE")
                        .HasMaxLength(51)
                        .HasColumnType("TEXT");

                    b.Property<string>("DISTRICT")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NAME")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("TOWN")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("LOGICALREF");

                    b.ToTable("Institutions");
                });
#pragma warning restore 612, 618
        }
    }
}
