// <auto-generated />
using System;
using EKYNOX_HEI.DATA.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EKYNOX_HEI.DATA.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("EKYNOX_HEI.DATA.DataModel.EducationAttendance", b =>
                {
                    b.Property<int>("LOGICALREF")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DATE_")
                        .HasColumnType("TEXT");

                    b.Property<string>("DOCNO")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EDUCATIONFULLNAME")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("FILENAME")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("FILEPATH")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("INSTUTIONREF")
                        .HasColumnType("INTEGER");

                    b.HasKey("LOGICALREF");

                    b.ToTable("EducationAttendance");
                });

            modelBuilder.Entity("EKYNOX_HEI.DATA.DataModel.Institutions", b =>
                {
                    b.Property<int>("LOGICALREF")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ADDRESS")
                        .HasMaxLength(700)
                        .HasColumnType("TEXT");

                    b.Property<string>("CITY")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CODE")
                        .HasMaxLength(51)
                        .HasColumnType("TEXT");

                    b.Property<string>("DISTRICT")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NAME")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("TOWN")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("LOGICALREF");

                    b.ToTable("Institutions");
                });

            modelBuilder.Entity("EKYNOX_HEI.DATA.DataModel.Users", b =>
                {
                    b.Property<int>("LOGICALREF")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EMAIL")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NAME")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("NR")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PASSWORD")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("PHONE")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("ROLE")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SURNAME")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("USERNAME")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("LOGICALREF");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
